### ISSUE TITLE
移除 Rust

### ISSUE THREAD

**Issue by Dianliang233** [iewnfod/CAIE_Code#2]
### 功能描述

貌似找 Python 这样的功能在头上加一层 Rust 还是有点太笨重了吧（

不如用 sh & pwsh 重新实现一遍，这样也省掉 build 了

**Comment by iewnfod** [comment]
如果使用 sh / pwsh，可以做成没有后缀名的文件吗？同时，如果未来需要实现一些功能上的操作，使用sh书写感觉会非常复杂

**Comment by iewnfod** [comment]
至于所谓的笨重，确实有点，但是也还好吧，也不会对性能有什么损耗之类的

**Comment by Dianliang233** [comment]
要不然这个wrapper也不要了，干脆传pypi，这样install也方便

**Comment by iewnfod** [comment]
用pip的话，我就无法做到行内自己更新了，也挺麻烦的
这种东西我觉得就各有好坏吧（只不过我用的方法就是缺点比较多），想用啥用啥，反正能跑就行
而且换个启动方式，我很多启动时的参数解析和逻辑都要重写（懒

**Comment by Dianliang233** [comment]
> 用pip的话，我就无法做到行内自己更新了，也挺麻烦的
也不是不能做到，如果有更新可以把spawn一个pip出来更新

> 而且换个启动方式，我很多启动时的参数解析和逻辑都要重写（懒
我可以pr（

**Comment by iewnfod** [comment]
hhh
算了吧，改起来烦死了
其实你可以帮我改一下那个case的语法，把句末的分号去掉，这一块我一直不知道怎么改

**Comment by iewnfod** [comment]
我觉得你可以自己fork一下，然后实现你的这样想法，就相当于为我这个项目添加一个安装方式，怎么样

**Comment by iewnfod** [comment]
Finish shell script support for macOS and linux

**Comment by lightumcc** [comment]
> Finish shell script support for macOS and linux

那么如何解决Windows的问题

**Comment by iewnfod** [comment]
现已发现shell脚本的很多弊端
