### ISSUE TITLE
Error in type arrays

### ISSUE THREAD

**Issue by Dan-k391** [iewnfod/CAIE_Code#4]
### 问题描述

The follow code gives a error
```
TYPE shit
	DECLARE i:INTEGER
ENDTYPE

DECLARE arr: ARRAY[1:10] OF shit

arr[3].i <- 8

OUTPUT arr[3].i
```
![image](https://github.com/iewnfod/CAIE_Code/assets/73747609/b6688971-6e1c-4b30-8eae-ea1534e6f8ea)

### 复现方法

Run the following code
```
TYPE shit
	DECLARE i:INTEGER
ENDTYPE

DECLARE arr: ARRAY[1:10] OF shit

arr[3].i <- 8

OUTPUT arr[3].i
```

### 操作系统类型

Windows

### 操作系统版本

win10

### Python版本

3.8.5

### 额外说明

太烂了赶紧修复

**Comment by iewnfod** [comment]
声明和赋值已经修复，output还存在问题

**Comment by iewnfod** [comment]
<img width="232" alt="截屏2023-09-21 08 52 56" src="https://github.com/iewnfod/CAIE_Code/assets/108739262/ff9054de-bd58-41e5-971b-673082897782">
已修复所有问题
