### ISSUE TITLE
"INTPUT"

### ISSUE THREAD

**Issue by Feliks-WR** [iewnfod/CAIE_Code#80]
### 问题描述

When I type "Input", it writes "Intput"

### 复现方法

Type Input

### 版本信息

0.1.6

**Comment by lightumcc** [comment]
Did you mean that you type `Input` directly in your terminal?

**Comment by lightumcc** [comment]
I understand. This is a bug from CPCIE, it will be fixed in the next version.
Thanks for your report

**Comment by lightumcc** [comment]
https://github.com/iewnfod/CAIE-Code-Extension/commit/5884c9b48b683f8e36fe8e15fa043c38c7e97adf
